s=input()
# for s in range(1,9):
#     print(s,end="")
#8번 출력하는걸 프로그램으로 만들어주세요
# print(s,end="")
# print(s,end="")
# print(s,end="")
# print(s,end="")
# print(s,end="")
# print(s,end="")
# print(s,end="")
# print(s,end="")
# print(1)
# print(2)
# print(3)
# print(4)
# print(5)
# print(6)
# print(7)
# print(8)
# print(9)
# print(10)
# for i in range(1,11)
# for i in range(1,11)
#     print(1)
for i in range(1,9):
    print(s,end="")